-- Question 1
SELECT * 
FROM COUNTRY 
ORDER BY NAME;

-- Question 2
SELECT ORGANIZATION, NB
FROM (
        SELECT ORGANIZATION, COUNT(*) NB
        FROM ISMEMBER 
        GROUP BY ORGANIZATION)
WHERE NB IN 
(
    SELECT MAX(NB)
    FROM 
    (
        SELECT ORGANIZATION, COUNT(*) NB
        FROM ISMEMBER 
        GROUP BY ORGANIZATION
    )
);

-- Question 3
SELECT NAME, CODE, (POPCIT/POPULATION)*100 POURCENTAGE
FROM COUNTRY C LEFT JOIN (
    SELECT COUNTRY, SUM(POPULATION) POPCIT
    FROM CITY
    WHERE POPULATION IS NOT NULL
    GROUP BY COUNTRY
)P ON C.CODE = P.COUNTRY
ORDER BY POURCENTAGE;

-- Question 4
SELECT CONTINENT, TRUNC(SUM(POPULATION*PERCENTAGE/100),0) POP FROM COUNTRY C JOIN ENCOMPASSES E ON C.CODE = E.COUNTRY GROUP BY CONTINENT ORDER BY POP;

-- Question 5
SELECT COUNTRY1, L1+L2 LENGTH
FROM
    (SELECT COUNTRY1, SUM(LENGTH) L1 FROM BORDERS GROUP BY COUNTRY1) B1 JOIN
    (SELECT COUNTRY2, SUM(LENGTH) L2 FROM BORDERS GROUP BY COUNTRY2) B2 ON B1.COUNTRY1 = B2.COUNTRY2
ORDER BY LENGTH;

-- Question 6
WITH CITIES(NAME, COUNTRY) AS
(
    SELECT DISTINCT NAME, COUNTRY FROM CITY
)

SELECT NAME, COUNT(*) NB 
FROM CITIES 
GROUP BY NAME 
HAVING COUNT(*) > 1 
ORDER BY NB, NAME;

-- Question 7
SELECT NAME, CODE FROM COUNTRY WHERE CODE NOT IN (SELECT CODE FROM POLITICS)
UNION
SELECT NAME, CODE FROM COUNTRY WHERE CODE IN (SELECT COUNTRY FROM POLITICS WHERE INDEPENDENCE IS NULL);

-- Question 8
SELECT NAME, CODE FROM COUNTRY WHERE CODE NOT IN (SELECT COUNTRY FROM ISMEMBER);

-- Question 9
SELECT NAME, ORGANIZATION FROM COUNTRY C LEFT JOIN ISMEMBER I ON C.CODE = I.COUNTRY ORDER BY NAME;


-- Question 10

--TODO

-- Question 11

--TODO

-- Question 12
SELECT DISTINCT NAME 
FROM CITY 
WHERE NAME IN (
  SELECT CITY 
  FROM ORGANIZATION) 
ORDER BY NAME;